### ISSUE TITLE
Update all the RoboRios & laptops to 2018 image/wpilib/robotpy stuff

### ISSUE THREAD

**Issue by a2aaron** [FRC1076/2018-Competition#1]
See http://robotpy.readthedocs.io/en/stable/install/robot.html#install-robotpy for instructions

**Comment by a2aaron** [comment]
This is almost done on the purple robot! I need to still figure out how install robotpy-ctre.

I've made a Slack document detailing what to do to update everything here: https://frc1076software.slack.com/files/U0JL51VHB/F8S33TUP2/Tips_and_Tricks_for_Updating_Everything_to_2018

**Comment by a2aaron** [comment]
Done: Computer A, Computer C (Computer B is broken)
Purple robot, 1 Rio on the Test Robot

**Comment by Dannihu01** [comment]
We finished this right? I can close this?
